In [1]:
import os
import tkinter as tk
from tkinter import Text,filedialog
from tkinter import *
from PIL import Image,ImageTk
from keras.preprocessing import image
from keras.models import load_model
import numpy as np

Using TensorFlow backend.


In [2]:
def load_processed_model():
    model = load_model('D:\Programs\Python\Projects\Skin-Cancer-Localization-And-Classification\Skin_Cancer(Classification).h5')
    return model

In [3]:
root = tk.Tk()
root.title('Skin Cancer Classification')
canvas = Canvas(width=250, height=250, bg='white')
canvas.pack()
root.iconbitmap(r'D:\Photos & Videos\Logo1.ico')

model = load_processed_model()
def Find():
    img_file = filedialog.askopenfilename(title='Select Image',filetypes=[("Image File",'.jpg')])
    img_display = Image.open(img_file)
    pic = ImageTk.PhotoImage(img_display)
    pic_label = Label(canvas,image = pic)
    pic_label.image=pic
    pic_label.grid(row=0,column=0)

    res = image.load_img(img_file,target_size=(224,224))
    res = image.img_to_array(res)
    res = np.expand_dims(res,axis=0)
    res = res/255

    window1  = Toplevel()
    window1.iconbitmap(r'D:\Photos & Videos\Logo1.ico')
    output = model.predict(res)
    print(output)
    if(output[0][0]>output[0][1]):
        text1="Chances of Cancer " + str(round(100-output[0][0]*100,2))+"%"
        lbl = Label(window1,text=text1).pack()
    else:
        text2="Chances of Cancer " + str(round(output[0][1]*100,2)) +"%"
        lbl = Label(window1,text=text2).pack()
openfile = tk.Button(root,text="Open Image",padx=10,pady=5,fg="black",command = Find)
openfile.pack()
root.mainloop()

[[0.2076816 0.858712 ]]
[[0.90415335 0.10654212]]
[[9.9985027e-01 1.5060589e-04]]
[[0.2076816 0.858712 ]]
[[9.9999988e-01 5.7514633e-08]]
[[0.5354049  0.32654503]]
